#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['pip',
 'pip._internal',
 'pip._internal.cli',
 'pip._internal.commands',
 'pip._internal.distributions',
 'pip._internal.index',
 'pip._internal.locations',
 'pip._internal.metadata',
 'pip._internal.metadata.importlib',
 'pip._internal.models',
 'pip._internal.network',
 'pip._internal.operations',
 'pip._internal.operations.build',
 'pip._internal.operations.install',
 'pip._internal.req',
 'pip._internal.resolution',
 'pip._internal.resolution.legacy',
 'pip._internal.resolution.resolvelib',
 'pip._internal.utils',
 'pip._internal.vcs',
 'pip._vendor',
 'pip._vendor.cachecontrol',
 'pip._vendor.cachecontrol.caches',
 'pip._vendor.certifi',
 'pip._vendor.dependency_groups',
 'pip._vendor.distlib',
 'pip._vendor.distro',
 'pip._vendor.idna',
 'pip._vendor.msgpack',
 'pip._vendor.packaging',
 'pip._vendor.packaging.licenses',
 'pip._vendor.pkg_resources',
 'pip._vendor.platformdirs',
 'pip._vendor.pygments',
 'pip._vendor.pygments.filters',
 'pip._vendor.pygments.formatters',
 'pip._vendor.pygments.lexers',
 'pip._vendor.pygments.styles',
 'pip._vendor.pyproject_hooks',
 'pip._vendor.pyproject_hooks._in_process',
 'pip._vendor.requests',
 'pip._vendor.resolvelib',
 'pip._vendor.resolvelib.resolvers',
 'pip._vendor.rich',
 'pip._vendor.tomli',
 'pip._vendor.tomli_w',
 'pip._vendor.truststore',
 'pip._vendor.urllib3',
 'pip._vendor.urllib3.contrib',
 'pip._vendor.urllib3.contrib._securetransport',
 'pip._vendor.urllib3.packages',
 'pip._vendor.urllib3.packages.backports',
 'pip._vendor.urllib3.util']

package_data = \
{'': ['*']}

package_dir = \
{'': 'src'}

entry_points = \
{'console_scripts': ['pip = pip._internal.cli.main:main',
                     'pip3 = pip._internal.cli.main:main']}

setup(name='pip',
      version='26.0',
      description='The PyPA recommended tool for installing Python packages.',
      author=None,
      author_email='The pip developers <distutils-sig@python.org>',
      url=None,
      packages=packages,
      package_data=package_data,
      package_dir=package_dir,
      entry_points=entry_points,
      python_requires='>=3.9',
     )
